---
abstract: 'Perl interface to the DNSwatch API'
author:
  - 'C Hutchinson <taint@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131560'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-DNSwatch
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: 0
  Test::More: 0
  URI::Escape: 0
  perl: 5.008005
version: 0.02
